// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// APIKeyPermissionProfile is the predicate function for apikeypermissionprofile builders.
type APIKeyPermissionProfile func(*sql.Selector)

// AuthFileQuotaSnapshot is the predicate function for authfilequotasnapshot builders.
type AuthFileQuotaSnapshot func(*sql.Selector)

// AuthFileQuotaSnapshotPoint is the predicate function for authfilequotasnapshotpoint builders.
type AuthFileQuotaSnapshotPoint func(*sql.Selector)

// AuthGroupModelOwnerMapping is the predicate function for authgroupmodelownermapping builders.
type AuthGroupModelOwnerMapping func(*sql.Selector)

// AuthSubjectQuotaCycle is the predicate function for authsubjectquotacycle builders.
type AuthSubjectQuotaCycle func(*sql.Selector)

// CcSwitchImportConfig is the predicate function for ccswitchimportconfig builders.
type CcSwitchImportConfig func(*sql.Selector)

// IdentityFingerprint is the predicate function for identityfingerprint builders.
type IdentityFingerprint func(*sql.Selector)

// ModelConfig is the predicate function for modelconfig builders.
type ModelConfig func(*sql.Selector)

// ModelOpenrouterSyncState is the predicate function for modelopenroutersyncstate builders.
type ModelOpenrouterSyncState func(*sql.Selector)

// ModelOwnerPreset is the predicate function for modelownerpreset builders.
type ModelOwnerPreset func(*sql.Selector)

// ModelPricing is the predicate function for modelpricing builders.
type ModelPricing func(*sql.Selector)

// ProxyPool is the predicate function for proxypool builders.
type ProxyPool func(*sql.Selector)

// RequestLog is the predicate function for requestlog builders.
type RequestLog func(*sql.Selector)

// RequestLogContent is the predicate function for requestlogcontent builders.
type RequestLogContent func(*sql.Selector)

// RoutingConfig is the predicate function for routingconfig builders.
type RoutingConfig func(*sql.Selector)

// RuntimeSetting is the predicate function for runtimesetting builders.
type RuntimeSetting func(*sql.Selector)
