// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "disabled", Type: field.TypeInt, Default: 0},
		{Name: "permission_profile_id", Type: field.TypeString, Default: ""},
		{Name: "daily_limit", Type: field.TypeInt, Default: 0},
		{Name: "total_quota", Type: field.TypeInt, Default: 0},
		{Name: "spending_limit", Type: field.TypeFloat64, Default: 0},
		{Name: "daily_spending_limit", Type: field.TypeFloat64, Default: 0},
		{Name: "concurrency_limit", Type: field.TypeInt, Default: 0},
		{Name: "rpm_limit", Type: field.TypeInt, Default: 0},
		{Name: "tpm_limit", Type: field.TypeInt, Default: 0},
		{Name: "allowed_models", Type: field.TypeString, Default: "[]"},
		{Name: "allowed_channels", Type: field.TypeString, Default: "[]"},
		{Name: "allowed_channel_groups", Type: field.TypeString, Default: "[]"},
		{Name: "system_prompt", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
	}
	// APIKeyPermissionProfilesColumns holds the columns for the "api_key_permission_profiles" table.
	APIKeyPermissionProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "daily_limit", Type: field.TypeInt, Default: 0},
		{Name: "total_quota", Type: field.TypeInt, Default: 0},
		{Name: "concurrency_limit", Type: field.TypeInt, Default: 0},
		{Name: "rpm_limit", Type: field.TypeInt, Default: 0},
		{Name: "tpm_limit", Type: field.TypeInt, Default: 0},
		{Name: "allowed_models", Type: field.TypeString, Default: "[]"},
		{Name: "allowed_channels", Type: field.TypeString, Default: "[]"},
		{Name: "allowed_channel_groups", Type: field.TypeString, Default: "[]"},
		{Name: "system_prompt", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
	}
	// APIKeyPermissionProfilesTable holds the schema information for the "api_key_permission_profiles" table.
	APIKeyPermissionProfilesTable = &schema.Table{
		Name:       "api_key_permission_profiles",
		Columns:    APIKeyPermissionProfilesColumns,
		PrimaryKey: []*schema.Column{APIKeyPermissionProfilesColumns[0]},
	}
	// AuthFileQuotaSnapshotsColumns holds the columns for the "auth_file_quota_snapshots" table.
	AuthFileQuotaSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date_key", Type: field.TypeString},
		{Name: "auth_index", Type: field.TypeString},
		{Name: "auth_subject_id", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "quota_key", Type: field.TypeString},
		{Name: "percent", Type: field.TypeFloat64, Nullable: true},
		{Name: "recorded_at", Type: field.TypeTime},
	}
	// AuthFileQuotaSnapshotsTable holds the schema information for the "auth_file_quota_snapshots" table.
	AuthFileQuotaSnapshotsTable = &schema.Table{
		Name:       "auth_file_quota_snapshots",
		Columns:    AuthFileQuotaSnapshotsColumns,
		PrimaryKey: []*schema.Column{AuthFileQuotaSnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authfilequotasnapshot_date_key_auth_index_quota_key",
				Unique:  true,
				Columns: []*schema.Column{AuthFileQuotaSnapshotsColumns[1], AuthFileQuotaSnapshotsColumns[2], AuthFileQuotaSnapshotsColumns[5]},
			},
			{
				Name:    "authfilequotasnapshot_auth_index",
				Unique:  false,
				Columns: []*schema.Column{AuthFileQuotaSnapshotsColumns[2]},
			},
			{
				Name:    "authfilequotasnapshot_auth_subject_id",
				Unique:  false,
				Columns: []*schema.Column{AuthFileQuotaSnapshotsColumns[3]},
			},
		},
	}
	// AuthFileQuotaSnapshotPointsColumns holds the columns for the "auth_file_quota_snapshot_points" table.
	AuthFileQuotaSnapshotPointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "recorded_at", Type: field.TypeTime},
		{Name: "auth_index", Type: field.TypeString},
		{Name: "auth_subject_id", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "quota_key", Type: field.TypeString},
		{Name: "quota_label", Type: field.TypeString, Default: ""},
		{Name: "percent", Type: field.TypeFloat64, Nullable: true},
		{Name: "reset_at", Type: field.TypeTime, Nullable: true},
		{Name: "window_seconds", Type: field.TypeInt64, Default: 0},
	}
	// AuthFileQuotaSnapshotPointsTable holds the schema information for the "auth_file_quota_snapshot_points" table.
	AuthFileQuotaSnapshotPointsTable = &schema.Table{
		Name:       "auth_file_quota_snapshot_points",
		Columns:    AuthFileQuotaSnapshotPointsColumns,
		PrimaryKey: []*schema.Column{AuthFileQuotaSnapshotPointsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authfilequotasnapshotpoint_auth_index_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{AuthFileQuotaSnapshotPointsColumns[2], AuthFileQuotaSnapshotPointsColumns[1]},
			},
			{
				Name:    "authfilequotasnapshotpoint_auth_index_quota_key_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{AuthFileQuotaSnapshotPointsColumns[2], AuthFileQuotaSnapshotPointsColumns[5], AuthFileQuotaSnapshotPointsColumns[1]},
			},
			{
				Name:    "authfilequotasnapshotpoint_auth_subject_id_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{AuthFileQuotaSnapshotPointsColumns[3], AuthFileQuotaSnapshotPointsColumns[1]},
			},
		},
	}
	// AuthGroupModelOwnerMappingsColumns holds the columns for the "auth_group_model_owner_mappings" table.
	AuthGroupModelOwnerMappingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "auth_group", Type: field.TypeString, Unique: true},
		{Name: "owner", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthGroupModelOwnerMappingsTable holds the schema information for the "auth_group_model_owner_mappings" table.
	AuthGroupModelOwnerMappingsTable = &schema.Table{
		Name:       "auth_group_model_owner_mappings",
		Columns:    AuthGroupModelOwnerMappingsColumns,
		PrimaryKey: []*schema.Column{AuthGroupModelOwnerMappingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authgroupmodelownermapping_owner",
				Unique:  false,
				Columns: []*schema.Column{AuthGroupModelOwnerMappingsColumns[2]},
			},
		},
	}
	// AuthSubjectQuotaCyclesColumns holds the columns for the "auth_subject_quota_cycles" table.
	AuthSubjectQuotaCyclesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subject_id", Type: field.TypeString},
		{Name: "auth_index", Type: field.TypeString, Default: ""},
		{Name: "provider", Type: field.TypeString, Default: ""},
		{Name: "quota_key", Type: field.TypeString},
		{Name: "cycle_start_at", Type: field.TypeTime},
		{Name: "reset_at", Type: field.TypeTime},
		{Name: "window_seconds", Type: field.TypeInt64, Default: 0},
		{Name: "last_verified_at", Type: field.TypeTime},
	}
	// AuthSubjectQuotaCyclesTable holds the schema information for the "auth_subject_quota_cycles" table.
	AuthSubjectQuotaCyclesTable = &schema.Table{
		Name:       "auth_subject_quota_cycles",
		Columns:    AuthSubjectQuotaCyclesColumns,
		PrimaryKey: []*schema.Column{AuthSubjectQuotaCyclesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authsubjectquotacycle_subject_id_quota_key",
				Unique:  true,
				Columns: []*schema.Column{AuthSubjectQuotaCyclesColumns[1], AuthSubjectQuotaCyclesColumns[4]},
			},
			{
				Name:    "authsubjectquotacycle_subject_id_window_seconds_last_verified_at",
				Unique:  false,
				Columns: []*schema.Column{AuthSubjectQuotaCyclesColumns[1], AuthSubjectQuotaCyclesColumns[7], AuthSubjectQuotaCyclesColumns[8]},
			},
		},
	}
	// CcswitchImportConfigsColumns holds the columns for the "ccswitch_import_configs" table.
	CcswitchImportConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "client_type", Type: field.TypeString},
		{Name: "provider_name", Type: field.TypeString, Default: ""},
		{Name: "note", Type: field.TypeString, Default: ""},
		{Name: "default_model", Type: field.TypeString, Default: ""},
		{Name: "model_mappings", Type: field.TypeString, Default: "[]"},
		{Name: "allowed_channel_groups", Type: field.TypeString, Default: "[]"},
		{Name: "route_path", Type: field.TypeString, Default: ""},
		{Name: "endpoint_path", Type: field.TypeString, Default: ""},
		{Name: "usage_auto_interval", Type: field.TypeInt, Default: 30},
		{Name: "api_key_field", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
	}
	// CcswitchImportConfigsTable holds the schema information for the "ccswitch_import_configs" table.
	CcswitchImportConfigsTable = &schema.Table{
		Name:       "ccswitch_import_configs",
		Columns:    CcswitchImportConfigsColumns,
		PrimaryKey: []*schema.Column{CcswitchImportConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ccswitchimportconfig_route_path",
				Unique:  true,
				Columns: []*schema.Column{CcswitchImportConfigsColumns[7]},
			},
		},
	}
	// IdentityFingerprintsColumns holds the columns for the "identity_fingerprints" table.
	IdentityFingerprintsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "account_key", Type: field.TypeString},
		{Name: "auth_subject_id", Type: field.TypeString, Default: ""},
		{Name: "client_product", Type: field.TypeString, Default: ""},
		{Name: "client_variant", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeString, Default: ""},
		{Name: "fields_json", Type: field.TypeString, Default: "{}"},
		{Name: "observed_headers_json", Type: field.TypeString, Default: "{}"},
		{Name: "created_at", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
		{Name: "last_seen_at", Type: field.TypeString, Default: ""},
	}
	// IdentityFingerprintsTable holds the schema information for the "identity_fingerprints" table.
	IdentityFingerprintsTable = &schema.Table{
		Name:       "identity_fingerprints",
		Columns:    IdentityFingerprintsColumns,
		PrimaryKey: []*schema.Column{IdentityFingerprintsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "identityfingerprint_provider_account_key",
				Unique:  true,
				Columns: []*schema.Column{IdentityFingerprintsColumns[1], IdentityFingerprintsColumns[2]},
			},
			{
				Name:    "identityfingerprint_provider_last_seen_at",
				Unique:  false,
				Columns: []*schema.Column{IdentityFingerprintsColumns[1], IdentityFingerprintsColumns[11]},
			},
		},
	}
	// ModelConfigsColumns holds the columns for the "model_configs" table.
	ModelConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model_id", Type: field.TypeString, Unique: true},
		{Name: "owned_by", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "enabled", Type: field.TypeInt, Default: 1},
		{Name: "input_modalities", Type: field.TypeString, Default: ""},
		{Name: "output_modalities", Type: field.TypeString, Default: ""},
		{Name: "pricing_mode", Type: field.TypeString, Default: "token"},
		{Name: "input_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "output_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cached_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cache_read_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cache_write_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "price_per_call", Type: field.TypeFloat64, Default: 0},
		{Name: "source", Type: field.TypeString, Default: "user"},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelConfigsTable holds the schema information for the "model_configs" table.
	ModelConfigsTable = &schema.Table{
		Name:       "model_configs",
		Columns:    ModelConfigsColumns,
		PrimaryKey: []*schema.Column{ModelConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelconfig_owned_by",
				Unique:  false,
				Columns: []*schema.Column{ModelConfigsColumns[2]},
			},
		},
	}
	// ModelOpenrouterSyncStateColumns holds the columns for the "model_openrouter_sync_state" table.
	ModelOpenrouterSyncStateColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "enabled", Type: field.TypeInt, Default: 0},
		{Name: "interval_minutes", Type: field.TypeInt, Default: 1440},
		{Name: "last_sync_at", Type: field.TypeString, Default: ""},
		{Name: "last_success_at", Type: field.TypeString, Default: ""},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "last_seen", Type: field.TypeInt, Default: 0},
		{Name: "last_added", Type: field.TypeInt, Default: 0},
		{Name: "last_updated", Type: field.TypeInt, Default: 0},
		{Name: "last_skipped", Type: field.TypeInt, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelOpenrouterSyncStateTable holds the schema information for the "model_openrouter_sync_state" table.
	ModelOpenrouterSyncStateTable = &schema.Table{
		Name:       "model_openrouter_sync_state",
		Columns:    ModelOpenrouterSyncStateColumns,
		PrimaryKey: []*schema.Column{ModelOpenrouterSyncStateColumns[0]},
	}
	// ModelOwnerPresetsColumns holds the columns for the "model_owner_presets" table.
	ModelOwnerPresetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "value", Type: field.TypeString, Unique: true},
		{Name: "label", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "enabled", Type: field.TypeInt, Default: 1},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelOwnerPresetsTable holds the schema information for the "model_owner_presets" table.
	ModelOwnerPresetsTable = &schema.Table{
		Name:       "model_owner_presets",
		Columns:    ModelOwnerPresetsColumns,
		PrimaryKey: []*schema.Column{ModelOwnerPresetsColumns[0]},
	}
	// ModelPricingColumns holds the columns for the "model_pricing" table.
	ModelPricingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model_id", Type: field.TypeString, Unique: true},
		{Name: "input_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "output_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cached_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cache_read_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cache_write_price_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ModelPricingTable holds the schema information for the "model_pricing" table.
	ModelPricingTable = &schema.Table{
		Name:       "model_pricing",
		Columns:    ModelPricingColumns,
		PrimaryKey: []*schema.Column{ModelPricingColumns[0]},
	}
	// ProxyPoolColumns holds the columns for the "proxy_pool" table.
	ProxyPoolColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeInt, Default: 1},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
	}
	// ProxyPoolTable holds the schema information for the "proxy_pool" table.
	ProxyPoolTable = &schema.Table{
		Name:       "proxy_pool",
		Columns:    ProxyPoolColumns,
		PrimaryKey: []*schema.Column{ProxyPoolColumns[0]},
	}
	// RequestLogsColumns holds the columns for the "request_logs" table.
	RequestLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "api_key", Type: field.TypeString, Default: ""},
		{Name: "api_key_id", Type: field.TypeString, Default: ""},
		{Name: "auth_subject_id", Type: field.TypeString, Default: ""},
		{Name: "api_key_name", Type: field.TypeString, Default: ""},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "upstream_model", Type: field.TypeString, Default: ""},
		{Name: "vision_fallback_model", Type: field.TypeString, Default: ""},
		{Name: "source", Type: field.TypeString, Default: ""},
		{Name: "channel_name", Type: field.TypeString, Default: ""},
		{Name: "auth_index", Type: field.TypeString, Default: ""},
		{Name: "failed", Type: field.TypeInt, Default: 0},
		{Name: "streaming", Type: field.TypeInt, Default: 0},
		{Name: "latency_ms", Type: field.TypeInt64, Default: 0},
		{Name: "first_token_ms", Type: field.TypeInt64, Default: 0},
		{Name: "input_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "reasoning_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "cached_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "cost", Type: field.TypeFloat64, Default: 0},
		{Name: "input_content", Type: field.TypeString, Default: ""},
		{Name: "output_content", Type: field.TypeString, Default: ""},
	}
	// RequestLogsTable holds the schema information for the "request_logs" table.
	RequestLogsTable = &schema.Table{
		Name:       "request_logs",
		Columns:    RequestLogsColumns,
		PrimaryKey: []*schema.Column{RequestLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "requestlog_timestamp",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[1]},
			},
			{
				Name:    "requestlog_api_key",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[2]},
			},
			{
				Name:    "requestlog_api_key_timestamp",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[2], RequestLogsColumns[1]},
			},
			{
				Name:    "requestlog_api_key_id",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[3]},
			},
			{
				Name:    "requestlog_api_key_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[3], RequestLogsColumns[1]},
			},
			{
				Name:    "requestlog_model",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[6]},
			},
			{
				Name:    "requestlog_failed",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[12]},
			},
			{
				Name:    "requestlog_auth_index",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[11]},
			},
			{
				Name:    "requestlog_auth_subject_id",
				Unique:  false,
				Columns: []*schema.Column{RequestLogsColumns[4]},
			},
		},
	}
	// RequestLogContentColumns holds the columns for the "request_log_content" table.
	RequestLogContentColumns = []*schema.Column{
		{Name: "log_id", Type: field.TypeInt64, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "compression", Type: field.TypeString, Default: "zstd"},
		{Name: "input_content", Type: field.TypeBytes, Nullable: true},
		{Name: "output_content", Type: field.TypeBytes, Nullable: true},
		{Name: "detail_content", Type: field.TypeBytes, Nullable: true},
		{Name: "session_id", Type: field.TypeString, Default: ""},
	}
	// RequestLogContentTable holds the schema information for the "request_log_content" table.
	RequestLogContentTable = &schema.Table{
		Name:       "request_log_content",
		Columns:    RequestLogContentColumns,
		PrimaryKey: []*schema.Column{RequestLogContentColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "requestlogcontent_timestamp",
				Unique:  false,
				Columns: []*schema.Column{RequestLogContentColumns[1]},
			},
			{
				Name:    "requestlogcontent_session_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{RequestLogContentColumns[6], RequestLogContentColumns[1]},
			},
		},
	}
	// RoutingConfigColumns holds the columns for the "routing_config" table.
	RoutingConfigColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "payload", Type: field.TypeString, Default: "{}"},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
	}
	// RoutingConfigTable holds the schema information for the "routing_config" table.
	RoutingConfigTable = &schema.Table{
		Name:       "routing_config",
		Columns:    RoutingConfigColumns,
		PrimaryKey: []*schema.Column{RoutingConfigColumns[0]},
	}
	// RuntimeSettingsColumns holds the columns for the "runtime_settings" table.
	RuntimeSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "setting_key", Type: field.TypeString, Unique: true},
		{Name: "payload", Type: field.TypeString, Default: "{}"},
		{Name: "updated_at", Type: field.TypeString, Default: ""},
	}
	// RuntimeSettingsTable holds the schema information for the "runtime_settings" table.
	RuntimeSettingsTable = &schema.Table{
		Name:       "runtime_settings",
		Columns:    RuntimeSettingsColumns,
		PrimaryKey: []*schema.Column{RuntimeSettingsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		APIKeyPermissionProfilesTable,
		AuthFileQuotaSnapshotsTable,
		AuthFileQuotaSnapshotPointsTable,
		AuthGroupModelOwnerMappingsTable,
		AuthSubjectQuotaCyclesTable,
		CcswitchImportConfigsTable,
		IdentityFingerprintsTable,
		ModelConfigsTable,
		ModelOpenrouterSyncStateTable,
		ModelOwnerPresetsTable,
		ModelPricingTable,
		ProxyPoolTable,
		RequestLogsTable,
		RequestLogContentTable,
		RoutingConfigTable,
		RuntimeSettingsTable,
	}
)

func init() {
	APIKeysTable.Annotation = &entsql.Annotation{
		Table: "api_keys",
	}
	APIKeyPermissionProfilesTable.Annotation = &entsql.Annotation{
		Table: "api_key_permission_profiles",
	}
	AuthFileQuotaSnapshotsTable.Annotation = &entsql.Annotation{
		Table: "auth_file_quota_snapshots",
	}
	AuthFileQuotaSnapshotPointsTable.Annotation = &entsql.Annotation{
		Table: "auth_file_quota_snapshot_points",
	}
	AuthGroupModelOwnerMappingsTable.Annotation = &entsql.Annotation{
		Table: "auth_group_model_owner_mappings",
	}
	AuthSubjectQuotaCyclesTable.Annotation = &entsql.Annotation{
		Table: "auth_subject_quota_cycles",
	}
	CcswitchImportConfigsTable.Annotation = &entsql.Annotation{
		Table: "ccswitch_import_configs",
	}
	IdentityFingerprintsTable.Annotation = &entsql.Annotation{
		Table: "identity_fingerprints",
	}
	ModelConfigsTable.Annotation = &entsql.Annotation{
		Table: "model_configs",
	}
	ModelOpenrouterSyncStateTable.Annotation = &entsql.Annotation{
		Table: "model_openrouter_sync_state",
	}
	ModelOwnerPresetsTable.Annotation = &entsql.Annotation{
		Table: "model_owner_presets",
	}
	ModelPricingTable.Annotation = &entsql.Annotation{
		Table: "model_pricing",
	}
	ProxyPoolTable.Annotation = &entsql.Annotation{
		Table: "proxy_pool",
	}
	RequestLogsTable.Annotation = &entsql.Annotation{
		Table: "request_logs",
	}
	RequestLogContentTable.Annotation = &entsql.Annotation{
		Table: "request_log_content",
	}
	RoutingConfigTable.Annotation = &entsql.Annotation{
		Table: "routing_config",
	}
	RuntimeSettingsTable.Annotation = &entsql.Annotation{
		Table: "runtime_settings",
	}
}
